export const columns = [
    { field: "id", headerName: "", width: 70 },
    { field: "address", headerName: "Address", width: 130 },
    { field: "postCode", headerName: "Post Code", width: 130 },
    { field: "type", headerName: "Property Type", width: 130 },
    { field: "numberOfRoom", headerName: "Number Of rooms", width: 130 },
    { field: "area", headerName: "Floor Area", width: 130 },
  ];
  
  export const rows = [
    {
      id: 1,
      address: "123 Main St",
      postCode: "ABC123",
      type: "Flat",
      area: 150,
      numberOfRoom: 3,
    },
    {
      id: 2,
      address: "456 Elm St",
      postCode: "DEF456",
      type: "Terraced House",
      area: 100,
      numberOfRoom: 2,
    },
    {
      id: 3,
      address: "789 Oak St",
      postCode: "GHI789",
      type: "Semi detachted",
      area: 120,
      numberOfRoom: 2,
    },
    {
      id: 4,
      address: "321 Pine St",
      postCode: "JKL321",
      type: "Flat",
      area: 200,
      numberOfRoom: 4,
    },
    {
      id: 5,
      address: "654 Cedar St",
      postCode: "MNO654",
      type: "Terraced House",
      area: 110,
      numberOfRoom: 1,
    },
    {
      id: 6,
      address: "987 Maple St",
      postCode: "PQR987",
      type: "Condo",
      area: 130,
      numberOfRoom: 3,
    },
    {
      id: 7,
      address: "135 Walnut St",
      postCode: "STU135",
      type: "Flat",
      area: 180,
      numberOfRoom: 3,
    },
    {
      id: 8,
      address: "246 Oak St",
      postCode: "VWX246",
      type: "Terraced House",
      area: 95,
      numberOfRoom: 2,
    },
    {
      id: 9,
      address: "369 Elm St",
      postCode: "YZA369",
      type: "Condo",
      area: 150,
      numberOfRoom: 2,
    },
    {
      id: 10,
      address: "111 Pine St",
      postCode: "BCD111",
      type: "Flat",
      area: 220,
      numberOfRoom: 5,
    },
    {
      id: 11,
      address: "222 Cedar St",
      postCode: "EFG222",
      type: "Terraced House",
      area: 105,
      numberOfRoom: 1,
    },
    {
      id: 12,
      address: "333 Maple St",
      postCode: "HIJ333",
      type: "Condo",
      area: 140,
      numberOfRoom: 3,
    },
    //
  ];